import React from "react";

import Payment from "../../components/payment/main";
import MetaTags from "../../components/Meta/CourseMetaTags";

function payment() {
  return (
    <div>
      <MetaTags
        title='Online Secure Payment - TekSlate' description='Generated by TekSlate INC '
        imgUrl='https://tekslateassets.s3.amazonaws.com/images/logo.svg' cannonical='payment' />
      <Payment />
    </div>
  );
}

export default payment;
