import React from "react";
import Category from "../../components/categoryComponent/category";
import MetaTags from "../../components/Meta/CourseMetaTags";

const categoryPage = () => {
  return (
    <div>
      <MetaTags
        title='TekSlate INC' description='Generated by TekSlate INC '
        imgUrl='https://tekslateassets.s3.amazonaws.com/images/logo.svg' cannonical='Category' />
      <Category />
    </div>
  );
};

export default categoryPage;
