import React from "react";
import LoginComponent from "../components/loginComponent/loginComponent";
import MetaTags from "../components/Meta/CourseMetaTags";
const LoginPage = () => {
  return (
    <div>
      <MetaTags
        title='TekSlate INC' description='Generated by TekSlate INC '
        imgUrl='https://tekslateassets.s3.amazonaws.com/images/logo.svg' cannonical='Login' />
      <LoginComponent />
    </div>
  );
};

export default LoginPage;
